export const choiceAdvantages: Record<string, string> = {
  'check-horses': 'Prevent a sabotaged harness from failing during the escort.',
  'inspect-pin': 'Keep the axle steady and prove that someone damaged it deliberately.',
  'delay-inspect': 'Leave with less hidden sabotage and a route prepared for an attack.',
  'rescue-family': 'Bring all three stranded farmers out of the flood alive.',
  'push-low': 'Reach the bridge before the river covers its first stones.',
  'read-flood': 'Find safer ground and spot the enemy signal on the ridge.',
  'take-tower': 'Silence the watcher and recover evidence of the planned ambush.',
  'shield-wagons': 'Keep the treaty wagon protected while crossing the exposed ridge.',
  'false-signal': 'Confirm that two enemy groups are coordinating around the escort.',
  'catch-saboteur': 'Capture a living witness who can expose the Crown plot.',
  'form-road-line': 'Meet the approaching riders as a ready shield formation.',
  'guard-wagon': 'Intercept the first attack aimed at the treaty wagon.',
  'command-speed': 'Reduce the time the attackers have to prepare their trap.',
  'swear-safe-arrival': 'Gain Oathfire and sense the people placed in immediate danger.',
  'tell-brann-seed': 'Let the guards protect Lysara as a second target before the ambush.',
  'guard-opening': 'Keep the opening volley away from the wounded and the wagon.',
  'command-opening': 'Prevent panic and move guards, horses, and wagon as one unit.',
  'spend-oathfire-opening': 'Find and prevent the next mortal blow before it lands.',
  'save-people-low': 'Save everyone trapped at the broken span.',
  'save-treaty-low': 'Keep the treaty intact while Brann rescues everyone trapped at the span.',
  'capture-low': 'Take an attacker alive and gain direct evidence of the conspiracy.',
  'save-mara-ridge': 'Save Mara and the wounded guard before the ledge collapses.',
  'hold-wagon-ridge': 'Keep the treaty safe while Brann rescues Mara and the guard.',
  'pursue-signaler': 'Capture the signaler carrying information about the ambush.',
  'break-riders': 'Break the encirclement while protecting both people and treaty.',
  'protect-lysara': 'Preserve Lysara, her living magic, and the treaty mission.',
  'take-leader': 'Capture the enemy leader alive for questioning.',
  'oath-line': 'Create a barrier that prevents the riders from reaching the wounded.',
  'treat-wounded': 'Stabilise Joren so he survives and can remember the attack.',
  'secure-ground': 'Create a defended refuge where evidence can be examined safely.',
  'question-prisoner': 'Learn that the enemy prepared orders for every possible route.',
  'turn-west': 'Keep the wounded away from the attackers who fled east.',
  'press-bellweather': 'Reach the nearest shelter and continue the treaty mission.',
  'climb-scout': 'See the altered landscape before committing the wounded escort.',
  'take-high-ground': 'Gain defensible ground, a clear view, and additional Wayfire.',
  'swear-home-oath': 'Gain Oathfire, additional Wayfire, and a magical path toward safety.',
  'c2-shield-arrival': 'A tight shield wall should bring every wounded traveller through the flooded yard together.',
  'c2-lead-water': 'Making yourself the nearest target should draw the mire hound away from the wounded.',
  'c2-oath-guided-entry': 'Your Oath should reveal the person the creature is most likely to reach first.',
  'c2-search-threshold': 'A careful search could expose hidden attackers and locate the threatened exits.',
  'c2-carry-first': 'Immediate pressure should slow Nilo’s bleeding before his condition becomes fatal.',
  'c2-organise-care': 'Clear assignments should replace panic with useful treatment reports.',
  'c2-work-beside-mara': 'Working beside Mara should slow Nilo’s bleeding and reveal how badly the leg is damaged.',
  'c2-medicine-lysara': 'The full dose should save Lysara’s hand, living magic, and treaty work.',
  'c2-medicine-nilo': 'The full dose should save Nilo’s injured leg from permanent damage.',
  'c2-medicine-attacker': 'The full dose should keep Garran alive long enough to testify against Ordan.',
  'c2-compare-memories': 'Matching maps and memories should expose a true route through the distortion.',
  'c2-ledger-route': 'The ledger could provide written evidence connecting Ordan to the siege preparations.',
  'c2-cellar-route': 'Searching below should reveal the hidden entrance and what the enemy is moving.',
  'c2-ask-missing-mara': 'Mara may recover the cut note while the close work strengthens her trust.',
  'c2-break-bracket': 'Cutting the rope should delay the theft and free an iron key for a safer route.',
  'c2-follow-footsteps': 'Following the prints should expose the concealed pantry entrance.',
  'c2-demand-employer': 'A private countersign could tie Garran’s story directly to Ordan.',
  'c2-anchor-people': 'The shield line should keep the wounded beyond the attackers’ reach.',
  'c2-hold-door': 'Holding the pantry should keep the mire hound away from the wounded.',
  'c2-oath-anchor': 'Binding each life to your awareness should stop the shifting inn from taking anyone unseen.',
  'c2-order-no-fight': 'One disciplined shield wall should protect the wounded and clear the cellar route.',
  'c2-protect-current-group': 'A hard push should reach the cellar before the pantry fight traps the group.',
  'c2-block-versions': 'A heavy barricade should delay the soldiers long enough to choose a companion.',
  'c2-follow-companion': 'Your companion’s speciality may reveal a path your own senses cannot find.',
  'c2-feel-oath-pin': 'Touching the pin through your Oath should reveal the distant lives at risk.',
  'c2-command-pull': 'Precise timing should reseat the pin while preserving Health and Oathfire.',
  'c2-strength-pull': 'Immediate force should reseat the pin while preserving Command, Oathfire, and the wagon.',
  'c2-oath-pull': 'A binding promise should reseat the pin and return Oathfire for the road ahead.',
  'c2-swear-crown-truth': 'A public Oath should create proof Harrowfen can test while restoring Oathfire.',
  'c3-shield-wounded': 'Your shield should get the wounded through the gate while earning Mara’s trust.',
  'c3-give-command-word': 'Giving Elene temporary authority should win entry for the wounded.',
  'c3-catch-archive-spy': 'A fast capture should preserve Ordan’s signed request and the soldier burning it.',
  'c3-hold-healer-door': 'Holding the doorway should keep every patient safe and strengthen your authority.',
  'c3-show-nilo-memory': 'Your shield should keep Garran alive long enough to identify Ordan’s guard.',
  'c3-command-canal-line': 'A divided guard line should protect both rooms and trap an intruder.',
  'c3-mark-false-door': 'Firm pressure should force Varris to reveal the true bridge map.',
  'c3-seize-mask': 'A close attack should save Varris and recover Ordan’s murder order.',
  'c3-rush-burning-house': 'The direct route should reach Ordan’s safe room before the order burns.',
  'c3-order-streets-closed': 'Closing the streets should deny Ordan every ordinary escape road.',
  'c3-free-future-cloak': 'The rescued scout should reveal the fastest route across the market.',
  'c3-destroy-future-room': 'Burning the opening word should delay Ordan at the east arch.',
  'c3-name-the-real-plan': 'A balanced deployment should protect the wounded while keeping the fragment watched.',
  'c3-command-market': 'Clear orders should save the crowd and expose Ordan’s disguised soldiers.',
  'c3-carry-children': 'The rescue may earn a safe route through the market crowd.',
  'c3-use-oath-sight': 'A public Oath should expose Renn as the false captain.',
  'c3-disarm-double': 'A quick disarm should stop Renn from warning the bridge guards.',
  'c3-ask-future-warning': 'Pressure on Renn should reveal where Ordan plans to join the fragments.',
  'c3-cut-glove': 'Cutting the glove should stop Ordan closing the road behind him.',
  'c3-order-volley': 'The volley should force Ordan onto a narrower crossing with fewer defenders.',
  'c3-save-healing-house': 'The rescue should bring every trapped patient out alive.',
  'c3-keep-courier-in-sight': 'Staying close should reach the east arch before Ordan hides his route.',
  'c3-oath-hold-harrowfen': 'The new Oath should stabilise Harrowfen while returning fire for the pursuit.',
  'c3-use-oath-trail': 'Your Oath should find the correct bridge path before the trail closes.',
};
