export const choiceAdvantages: Record<string, string> = {
  'check-horses': 'Prevent a sabotaged harness from failing during the escort.',
  'inspect-pin': 'Keep the axle steady and prove that someone damaged it deliberately.',
  'delay-inspect': 'Leave with less hidden sabotage and a route prepared for an attack.',
  'rescue-family': 'Bring all three stranded farmers out of the flood alive.',
  'push-low': 'Reach the bridge before the river covers its first stones.',
  'read-flood': 'Find safer ground and spot the enemy signal on the ridge.',
  'take-tower': 'Silence the watcher and recover evidence of the planned ambush.',
  'shield-wagons': 'Keep the treaty wagon protected while crossing the exposed ridge.',
  'false-signal': 'Confirm that two enemy groups are coordinating around the escort.',
  'catch-saboteur': 'Capture a living witness who can expose the Crown plot.',
  'form-road-line': 'Meet the approaching riders as a ready shield formation.',
  'guard-wagon': 'Intercept the first attack aimed at the treaty wagon.',
  'command-speed': 'Reduce the time the attackers have to prepare their trap.',
  'swear-safe-arrival': 'Gain Oathfire and sense the people placed in immediate danger.',
  'tell-brann-seed': 'Let the guards protect Lysara as a second target before the ambush.',
  'guard-opening': 'Keep the opening volley away from the wounded and the wagon.',
  'command-opening': 'Prevent panic and move guards, horses, and wagon as one unit.',
  'spend-oathfire-opening': 'Find and prevent the next mortal blow before it lands.',
  'save-people-low': 'Save Joren and the trapped children from the collapsing bridge.',
  'save-treaty-low': 'Keep the treaty intact while Brann frees the trapped guard.',
  'capture-low': 'Take an attacker alive and gain direct evidence of the conspiracy.',
  'save-mara-ridge': 'Save Mara and the wounded guard before the ledge collapses.',
  'hold-wagon-ridge': 'Keep the treaty safe while Brann rescues Mara and the guard.',
  'pursue-signaler': 'Capture the signaler carrying information about the ambush.',
  'break-riders': 'Break the encirclement while protecting both people and treaty.',
  'protect-lysara': 'Preserve Lysara, her living magic, and the treaty mission.',
  'take-leader': 'Capture the enemy leader alive for questioning.',
  'oath-line': 'Create a barrier that prevents the riders from reaching the wounded.',
  'treat-wounded': 'Stabilise Joren so he survives and can remember the attack.',
  'secure-ground': 'Create a defended refuge where evidence can be examined safely.',
  'question-prisoner': 'Learn that the enemy prepared orders for every possible route.',
  'turn-west': 'Keep the wounded away from the attackers who fled east.',
  'press-bellweather': 'Reach the nearest shelter and continue the treaty mission.',
  'climb-scout': 'See the altered landscape before committing the wounded escort.',
  'take-high-ground': 'Gain defensible ground, a clear view, and additional Wayfire.',
  'swear-home-oath': 'Gain Oathfire, additional Wayfire, and a magical path toward safety.',
  'c2-shield-arrival': 'Bring every wounded traveller through the flooded yard together.',
  'c2-lead-water': 'Draw the mire hound away from the wounded as they enter the inn.',
  'c2-oath-guided-entry': 'Find the person the creature is most likely to reach first.',
  'c2-search-threshold': 'Confirm the common room is safe and locate the threatened exits.',
  'c2-carry-first': 'Slow Nilo’s bleeding before his condition becomes fatal.',
  'c2-organise-care': 'Replace panic with clear treatment and reveal each patient’s danger.',
  'c2-work-beside-mara': 'Slow Nilo’s bleeding, understand his injury, and gain Mara’s trust.',
  'c2-medicine-lysara': 'Save Lysara’s hand, living magic, and ability to complete the treaty.',
  'c2-medicine-nilo': 'Save Nilo’s injured leg from permanent damage.',
  'c2-medicine-attacker': 'Keep Sable alive as a public witness against Ordan.',
  'c2-compare-memories': 'Understand the road distortion and identify the true tunnel later.',
  'c2-ledger-route': 'Secure written evidence connecting Ordan to the siege preparations.',
  'c2-cellar-route': 'Discover the enemy entrance and how the road pin is being moved.',
  'c2-ask-missing-mara': 'Recover Ordan’s hidden note and strengthen Mara’s trust.',
  'c2-break-bracket': 'Delay the pin theft and take the iron key needed for a safer route.',
  'c2-follow-footsteps': 'Find the concealed pantry entrance used by Ordan’s soldiers.',
  'c2-demand-employer': 'Connect the attackers to a royal command inside Greyhaven Palace.',
  'c2-anchor-people': 'Place the wounded behind a disciplined shield line.',
  'c2-hold-door': 'Keep the mire hound away from the wounded during the siege.',
  'c2-oath-anchor': 'Prevent anyone inside the shifting inn from disappearing.',
  'c2-order-no-fight': 'Create an organised shield wall and clear the cellar route.',
  'c2-protect-current-group': 'Reach the cellar without losing anyone in the pantry fight.',
  'c2-block-versions': 'Delay the soldiers and gain time to choose the right companion.',
  'c2-follow-companion': 'Use your companion’s speciality to bypass the tunnel’s main danger.',
  'c2-feel-oath-pin': 'Sense the distant lives threatened by the damaged road pin.',
  'c2-command-pull': 'Reseat the pin intact while preserving Health and Oathfire.',
  'c2-strength-pull': 'Reseat the pin intact while preserving Command, Oathfire, and the wagon.',
  'c2-oath-pull': 'Reseat the pin intact and gain Oathfire for the promise ahead.',
  'c2-swear-crown-truth': 'Gain Oathfire and Wayfire while creating proof that can be tested publicly.',
  'c3-shield-wounded': 'Protect the wounded and gain Mara’s trust at Harrowfen’s gate.',
  'c3-give-command-word': 'Win entry for the wounded by giving Elene temporary authority.',
  'c3-catch-archive-spy': 'Preserve Ordan’s signed request and capture the soldier burning it.',
  'c3-hold-healer-door': 'Keep every patient safe and strengthen your authority with the guards.',
  'c3-show-nilo-memory': 'Keep Sable alive long enough to identify Ordan’s personal guard.',
  'c3-command-canal-line': 'Create a safe treatment area and trap one of Ordan’s intruders.',
  'c3-mark-false-door': 'Force Varris to reveal the true map of the Mileless Bridge.',
  'c3-seize-mask': 'Save Varris and recover Ordan’s written order to kill him.',
  'c3-rush-burning-house': 'Reach Ordan’s safe room before a route order burns.',
  'c3-order-streets-closed': 'Prevent Ordan from escaping by any ordinary road.',
  'c3-free-future-cloak': 'Save a town scout who reveals the fastest route across the market.',
  'c3-destroy-future-room': 'Destroy the bridge opening word and delay Ordan at the east arch.',
  'c3-name-the-real-plan': 'Protect the wounded while keeping the fragment under watch.',
  'c3-command-market': 'Save the main crowd and expose Ordan’s disguised soldiers.',
  'c3-carry-children': 'Save two children and gain a safe way through the market crowd.',
  'c3-use-oath-sight': 'Expose Renn as the false captain in front of Harrowfen.',
  'c3-disarm-double': 'Stop Renn from warning Ordan’s bridge guards or giving another order.',
  'c3-ask-future-warning': 'Learn where Ordan will join the two World Nail fragments.',
  'c3-cut-glove': 'Damage Ordan’s control glove so he cannot close the road behind him.',
  'c3-order-volley': 'Force Ordan onto a narrow, exposed crossing with fewer defenders.',
  'c3-save-healing-house': 'Bring every trapped patient out of the collapsing healing house.',
  'c3-keep-courier-in-sight': 'Reach the east arch before Ordan can hide his route.',
  'c3-oath-hold-harrowfen': 'Keep Harrowfen stable while gaining Oathfire for the pursuit.',
  'c3-use-oath-trail': 'Find the correct bridge path immediately and preserve the pursuit.',
};
